language: php


php:
 # - 5.4
  #- 5.5
  #- 5.6
  - hhvm
#  - hhvm-nightly


before_script:
  - ./.travis.install.sh
  - mkdir -p shippable/testresults
  - mkdir -p shippable/codecoverage

script:
  #- ./vendor/bin/phpunit
  -  ./vendor/bin/phpunit --log-junit shippable/testresults/junit.xml --coverage-xml shippable/codecoverage test/unit/


